{
    "name": "ISW IT Dashboard",
    "version": "19.0.1.6.1",
    "summary": "Operational data collection and reporting hub for IT, Helpdesk, NEO, and PC preparation",
    "category": "Operations/IT",
    "author": "ISW",
    "license": "LGPL-3",
    "depends": [
        "base",
        "mail",
        "web",
        "project",
        "hr",
    ],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/sequence.xml",
        "data/kpi_data.xml",
        "data/neo_question_data.xml",
        "views/helpdesk_monthly_target_views.xml",
        "views/helpdesk_monthly_summary_views.xml",
        "views/dashboard_period_views.xml",
        "views/dashboard_kpi_views.xml",
        "views/neo_views.xml",
        "views/pc_preparation_views.xml",
        "views/department_highlight_views.xml",
        "views/project_update_views.xml",
        "views/dashboard_views.xml",
        "views/menu.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "isw_it_dashboard/static/src/js/dashboard.js",
            "isw_it_dashboard/static/src/xml/dashboard.xml",
            "isw_it_dashboard/static/src/scss/dashboard.scss",
        ],
    },
    "application": True,
    "installable": True,
}
