from ...workable_api_connector.it_internal_dashboard.models import weekly_dashboard_mixin
from ...workable_api_connector.it_internal_dashboard.models import devops_dashboard
from ...workable_api_connector.it_internal_dashboard.models import helpdesk_juniorit_dashboard
from ...workable_api_connector.it_internal_dashboard.models import infra_dashboard
from ...workable_api_connector.it_internal_dashboard.models import compliance_dashboard
from ...workable_api_connector.it_internal_dashboard.models import management_dashboard
from ...workable_api_connector.it_internal_dashboard.models import dashboard_summary
from ...workable_api_connector.it_internal_dashboard.models import lighthouse_report_overview
from ...workable_api_connector.it_internal_dashboard.models import dashboard_summary_history
from ...workable_api_connector.it_internal_dashboard.models import dashboard_publication
from ...workable_api_connector.it_internal_dashboard.models import zoho_credentials
from ...workable_api_connector.it_internal_dashboard.models import zoho_sync_log