from . import weekly_dashboard_mixin
from . import devops_dashboard
from . import helpdesk_juniorit_dashboard
from . import infra_dashboard
from . import compliance_dashboard
from . import management_dashboard
from . import dashboard_summary
from . import lighthouse_report_overview
from . import dashboard_summary_history
from . import dashboard_publication
from . import zoho_credentials
from . import zoho_sync_log