{
    "name": "IT Internal Dashboard",
    "summary": "Internal IT dashboards with optional Zoho Desk synchronization",
    "description": """
IT Internal Dashboard
=====================
Provides weekly dashboards for Helpdesk, Infrastructure, DevOps, Compliance,
and Management, an executive summary, secure public dashboard publications,
and optional Zoho Desk synchronization.
    """,
    "version": "19.0.1.0.0",
    "category": "Productivity/Dashboard",
    "author": "IT Internal",
    "license": "OPL-1",
    "depends": ["base", "web", "website"],
    "external_dependencies": {"python": ["requests"]},
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "views/dashboard_menu.xml",
        "views/devops_dashboard_form_views.xml",
        "views/helpdesk_juniorit_dashboard_form_views.xml",
        "views/infra_dashboard_form_views.xml",
        "views/compliance_dashboard_form_views.xml",
        "views/management_dashboard_form_views.xml",
        "views/lighthouse_report_overview_forms.xml",
        "views/dashboard_summary_history_form_views.xml",
        "views/public_dashboard_templates.xml",
        "views/dashboard_publication_views.xml",
        "views/zoho_credentials_views.xml",
        "data/zoho_cron.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "it_internal_dashboard/static/src/js/chart.js",
            "it_internal_dashboard/static/src/summarized_dashboard/*",
            "it_internal_dashboard/static/src/devops_dashboard/*",
            "it_internal_dashboard/static/src/infra_dashboard/*",
            "it_internal_dashboard/static/src/helpdesk_dashboard/*",
            "it_internal_dashboard/static/src/compliance_dashboard/*",
            "it_internal_dashboard/static/src/management_dashboard/*",
        ],
        "web.assets_frontend": [
            "it_internal_dashboard/static/src/js/chart.js",
            "it_internal_dashboard/static/src/summarized_dashboard/*",
            "it_internal_dashboard/static/src/devops_dashboard/*",
            "it_internal_dashboard/static/src/infra_dashboard/*",
            "it_internal_dashboard/static/src/helpdesk_dashboard/*",
            "it_internal_dashboard/static/src/compliance_dashboard/*",
            "it_internal_dashboard/static/src/management_dashboard/*",
            "it_internal_dashboard/static/src/public_workspace/*",
        ],
    },
    "application": True,
    "installable": True,
}
